# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fechita',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
